### PR TITLE
feat(scripts): delete flow.begin events after processing

### LINKED ISSUE #104: Debigulate the data
There's a significant proportion of redundant data in our current dataset. We could:

* Delete all the `flow.continued...` events after using them to set the `continued_from` column in `flow_metadata`.

* Delete all the `flow.experiment...` events after using them to populate the `flow_experiments` table.

* Delete all the `flow.begin` and `flow.completed` events after using them to populate `flow_metadata` (be careful with this one, it might break some queries).

* Delete the `strict_multi_device_users` import job, which takes aaages and sometimes fails to finish at all.

* Send less performance events, just keep the ones we're actually using.

I estimate we could save about 5 gigabytes from our ~7 gigabyte per-day dataset size.

/cc @jbuck

### PR DESCRIPTION
**Pull request by philbooth**
Fixes #104.

This is the last thing I'm going to do about reducing the size of our data. `flow.completed` survives. Have pushed to the redshift helper for tomorrow morning's import, to check it's okay before merging.

@mozilla/fxa-devs

### CODE REVIEW

**Comment by philbooth** [comment]
```
fxa=# select count(*) from flow_events where type = 'flow.begin';
 count
-------
     0
(1 row)
```

**Review by vladikoff — APPROVED** [review]

**Comment by vladikoff** [comment]
@philbooth looks good, do we want final confirmation from @davismtl or @irrationalagent ?

**Comment by philbooth** [comment]
> do we want final confirmation from @davismtl or @irrationalagent ?

Well it's a bit late for that if we do, as I already deleted all the events. 😄

**Comment by irrationalagent** [comment]
for the record this was what we had agreed to do, so I'm fine with it.

**Pull request merged**
